insert into aerolineas (nombre) values ('Ankavandra Airport');
insert into aerolineas (nombre) values ('Suria Airport');
insert into aerolineas (nombre) values ('Witu Airport');
insert into aerolineas (nombre) values ('Larisa Airport');
insert into aerolineas (nombre) values ('Zhangjiakou Ningyuan Airport');
insert into aerolineas (nombre) values ('Guiglo Airport');
insert into aerolineas (nombre) values ('Gladwin Zettel Memorial Airport');
insert into aerolineas (nombre) values ('German Olano Airport');
insert into aerolineas (nombre) values ('Capitan FAP Jose A Quinones Gonzales International Airport');
insert into aerolineas (nombre) values ('San Salvador Airport');
insert into aerolineas (nombre) values ('Jamnagar Airport');
insert into aerolineas (nombre) values ('Ólafsfjörður Airport');
insert into aerolineas (nombre) values ('Kitakyūshū Airport');
insert into aerolineas (nombre) values ('Dallas Fort Worth International Airport');
insert into aerolineas (nombre) values ('Diebougou Airport');
insert into aerolineas (nombre) values ('Querétaro Intercontinental Airport');
insert into aerolineas (nombre) values ('Coban Airport');
insert into aerolineas (nombre) values ('Danbury Municipal Airport');
insert into aerolineas (nombre) values ('Glenwood Springs Municipal Airport');
insert into aerolineas (nombre) values ('Hakodate Airport');
insert into aerolineas (nombre) values ('Quesnel Airport');
insert into aerolineas (nombre) values ('Juist Airport');
insert into aerolineas (nombre) values ('Newcastle Airport');
insert into aerolineas (nombre) values ('Laguna Army Airfield');
insert into aerolineas (nombre) values ('Alluitsup Paa Heliport');
insert into aerolineas (nombre) values ('Hillenbrand Industries Airport');
insert into aerolineas (nombre) values ('Klokovo Airfield');
insert into aerolineas (nombre) values ('Buckley Air Force Base');
insert into aerolineas (nombre) values ('Paraguaçu Airport');
insert into aerolineas (nombre) values ('Negril Airport');
insert into aerolineas (nombre) values ('Barcelos Airport');
insert into aerolineas (nombre) values ('Baicheng Chang''an Airport');
insert into aerolineas (nombre) values ('Dominique Edward Osok Airport');
insert into aerolineas (nombre) values ('Kamembe Airport');
insert into aerolineas (nombre) values ('Statesville Regional Airport');
insert into aerolineas (nombre) values ('Batavia Downs Airport');
insert into aerolineas (nombre) values ('Corvo Airport');
insert into aerolineas (nombre) values ('April Point Seaplane Base');
insert into aerolineas (nombre) values ('El Bagre Airport');
insert into aerolineas (nombre) values ('Umba Airport');
insert into aerolineas (nombre) values ('Balıkesir Merkez Airport');
insert into aerolineas (nombre) values ('Playa del Carmen Airport');
insert into aerolineas (nombre) values ('Kishangarh Airport');
insert into aerolineas (nombre) values ('Guardiamarina Zañartu Airport');
insert into aerolineas (nombre) values ('Surat Thani Airport');
insert into aerolineas (nombre) values ('Presidente General Don Oscar D. Gestido International Airport');
insert into aerolineas (nombre) values ('Mörön Airport');
insert into aerolineas (nombre) values ('Lok Nayak Jayaprakash Airport');
insert into aerolineas (nombre) values ('Reykjavik Airport');
insert into aerolineas (nombre) values ('Dadu West Airport');
insert into aerolineas (nombre) values ('Jataí Airport');
insert into aerolineas (nombre) values ('Villa Gesell Airport');
insert into aerolineas (nombre) values ('Asapa Airport');
insert into aerolineas (nombre) values ('Taisha Airport');
insert into aerolineas (nombre) values ('Param Airport');
insert into aerolineas (nombre) values ('São Mateus Airport');
insert into aerolineas (nombre) values ('West Woodward Airport');
insert into aerolineas (nombre) values ('Chennai International Airport');
insert into aerolineas (nombre) values ('Akureyri Airport');
insert into aerolineas (nombre) values ('Bunia Airport');
insert into aerolineas (nombre) values ('Antsalova Airport');
insert into aerolineas (nombre) values ('Chico Municipal Airport');
insert into aerolineas (nombre) values ('Norfolk International Airport');
insert into aerolineas (nombre) values ('Libo Airport');
insert into aerolineas (nombre) values ('Animas Air Park');
insert into aerolineas (nombre) values ('Erzurum International Airport');
insert into aerolineas (nombre) values ('Marfa Municipal Airport');
insert into aerolineas (nombre) values ('Atsugi Naval Air Facility');
insert into aerolineas (nombre) values ('Le Castellet Airport');
insert into aerolineas (nombre) values ('Tabora Airport');
insert into aerolineas (nombre) values ('Vagar Airport');
insert into aerolineas (nombre) values ('Ulanqab Jining Airport');
insert into aerolineas (nombre) values ('Santa Barbara Municipal Airport');
insert into aerolineas (nombre) values ('Kitee Airport');
insert into aerolineas (nombre) values ('Igiugig Airport');
insert into aerolineas (nombre) values ('Noi Bai International Airport');
insert into aerolineas (nombre) values ('P C Pelser Airport');
insert into aerolineas (nombre) values ('Phifer Airfield');
insert into aerolineas (nombre) values ('Kashgar Airport');
insert into aerolineas (nombre) values ('Inhaminga Airport');
insert into aerolineas (nombre) values ('Trona Airport');
insert into aerolineas (nombre) values ('Tumbler Ridge Airport');
insert into aerolineas (nombre) values ('Jessore Airport');
insert into aerolineas (nombre) values ('Zaranj Airport');
insert into aerolineas (nombre) values ('Omega Airport');
insert into aerolineas (nombre) values ('Monterrey Airport');
insert into aerolineas (nombre) values ('Southampton Airport');
insert into aerolineas (nombre) values ('Bulolo Airport');
insert into aerolineas (nombre) values ('Barking Sands Airport');
insert into aerolineas (nombre) values ('Huesca/Pirineos Airport');
insert into aerolineas (nombre) values ('Kirk Field');
insert into aerolineas (nombre) values ('Jim Kelly Field');
insert into aerolineas (nombre) values ('Pietermaritzburg Airport');
insert into aerolineas (nombre) values ('Danilo Atienza Air Base');
insert into aerolineas (nombre) values ('Termas de Río Hondo international Airport');
insert into aerolineas (nombre) values ('Columbus Air Force Base');
insert into aerolineas (nombre) values ('Baise Youjiang Airport');
insert into aerolineas (nombre) values ('Tapeta Airport');
insert into aerolineas (nombre) values ('Lawrence J Timmerman Airport');
insert into aerolineas (nombre) values ('Dean River Airport');