insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (201, 85, 'V12 Vantage', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 64, 'Escalade EXT', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 86, 'Bravada', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 98, 'Spectra', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (225, 79, 'Truck', 12);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (300, 67, 'Diamante', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 86, 'Ram 3500', 92);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (252, 63, 'Tercel', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (130, 60, 'Silverado', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (269, 89, 'Element', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (106, 75, 'Regal', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 68, 'XK Series', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (118, 78, 'S-Series', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (181, 68, 'STS', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (192, 71, 'Grand Cherokee', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (171, 82, '626', 15);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (122, 68, 'Continental Mark VII', 64);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (286, 61, 'Civic', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 62, 'Impala SS', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (144, 85, '7 Series', 42);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (159, 77, 'Seville', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (261, 62, 'X3', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (228, 70, 'Gallardo', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (256, 86, 'D250 Club', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (135, 95, 'Corvette', 9);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (289, 60, 'A8', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (223, 84, 'Expo', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (212, 94, 'Aerostar', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (149, 99, 'GX', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (183, 84, 'Elan', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 79, 'Frontier', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (153, 92, 'E-Class', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (164, 99, 'Spectra', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (104, 100, 'Ram Van 2500', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (281, 68, 'G-Series 1500', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 69, 'C70', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 71, 'Altima', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (197, 84, 'Thunderbird', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (281, 65, 'Grand Caravan', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 75, 'Park Avenue', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (299, 94, 'Vanagon', 81);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (197, 97, '100', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 73, 'Pathfinder Armada', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (201, 80, 'LeSabre', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (285, 98, 'Taurus', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (107, 60, 'Odyssey', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (116, 92, '9-2X', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (110, 99, 'Neon', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (219, 91, 'Mustang', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (169, 83, 'Savana 1500', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (121, 85, 'Voyager', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (133, 94, 'Odyssey', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (206, 73, 'SLS AMG', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (134, 73, 'Lumina', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (116, 62, 'Ram Van B250', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 85, 'S10', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (224, 83, 'Cavalier', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 63, 'Bonneville', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 76, 'Passat', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (131, 87, 'Pathfinder', 15);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (238, 67, 'Continental Flying Spur', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 64, 'DBS', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 87, 'Eclipse', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 94, 'M5', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (231, 94, 'Cutlass Cruiser', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (125, 89, 'XK', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (268, 97, 'Patriot', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 90, 'RSX', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (134, 75, 'Discovery', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (202, 96, 'Ram Wagon B150', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 93, 'Mountaineer', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (149, 62, 'Summit', 81);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (119, 96, 'Sebring', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (206, 89, 'Lancer Evolution', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (293, 70, 'CC', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (252, 74, 'SSR', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 76, 'Suburban 2500', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (263, 98, 'Expedition', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (227, 92, 'Ridgeline', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (261, 88, 'Stylus', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (289, 71, 'Familia', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 66, 'IS', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 95, 'Vanagon', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (179, 71, 'Amanti', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (189, 74, 'Dakota Club', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (277, 73, 'Thunderbird', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (126, 65, 'LeSabre', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (283, 75, 'Grand Vitara', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (201, 72, 'F-Series', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (297, 66, 'Metro', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 81, 'Laser', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 61, 'Durango', 78);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (292, 75, 'Safari', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (223, 76, 'C70', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (159, 95, 'Stratus', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 95, '5000S', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 63, 'Trans Sport', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 96, 'RL', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (297, 98, 'E-Series', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (169, 73, 'Grand Vitara', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (238, 62, 'Mazdaspeed 3', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (259, 100, 'Probe', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (185, 68, 'Camaro', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (245, 76, 'M5', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (114, 64, 'Dakota', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (187, 89, 'xB', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (196, 79, 'Ion', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (252, 96, '928', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 85, 'Suburban 2500', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 67, 'Somerset', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (111, 92, 'Taurus', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 87, 'Tacoma', 14);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 65, 'Bonneville', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (234, 90, 'Silverado', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 82, 'Vandura 1500', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 60, 'Xterra', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (240, 90, 'Elan', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (225, 60, 'Pathfinder', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (181, 60, 'Maxima', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (184, 71, 'Bonneville', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 89, 'Expedition', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (245, 91, 'Sedona', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (109, 60, 'C8', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (293, 71, 'Civic', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (271, 94, 'Legacy', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (194, 82, 'Savana', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (262, 85, 'Silverado 3500', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (225, 86, 'Corvette', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (229, 75, 'Cavalier', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 79, 'Colorado', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (260, 65, 'Topaz', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 70, 'S6', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (278, 60, 'Ram Van B350', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 63, 'Town Car', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (216, 72, 'Entourage', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (260, 77, 'H1', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (106, 89, 'Town Car', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (110, 99, 'Silverado', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 62, 'Sable', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (146, 69, 'VUE', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 90, 'F350', 99);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 67, 'LeSabre', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (247, 92, 'Tempest', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 64, 'GTI', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 90, '8 Series', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 97, 'Sonata', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (299, 74, 'Taurus', 92);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (159, 91, 'Sierra 2500', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (233, 65, 'Silverado 3500HD', 91);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (180, 68, 'E150', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 84, 'Odyssey', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (172, 89, 'Regal', 27);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (173, 98, '98', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (276, 81, 'R8', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (159, 72, 'Sorento', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (265, 97, 'Vitara', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 65, 'NSX', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 69, 'Savana 1500', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (296, 83, 'GTI', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (189, 86, 'Continental GTC', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 89, 'Protege', 70);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (262, 99, 'Highlander', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (292, 90, 'H2', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (208, 80, 'XK', 64);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (121, 74, 'Silverado Hybrid', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 75, 'E150', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 86, 'Town & Country', 9);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (298, 78, 'Escape', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 79, 'Solstice', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (204, 88, 'Dakota', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 78, 'Sedona', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 86, 'Accord', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (164, 86, 'Miata MX-5', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (290, 70, 'M', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (266, 91, 'Rabbit', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (169, 85, 'Grand Caravan', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (143, 92, 'Swift', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (250, 97, 'Wrangler', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (108, 60, 'Space', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 73, 'A8', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 66, 'Topaz', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (230, 76, 'Caravan', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (210, 68, 'Town & Country', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (183, 82, 'CTS-V', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (275, 96, 'G35', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (189, 68, 'IPL G', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 73, 'E-350 Super Duty', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 73, 'Malibu', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (262, 78, 'S10', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (146, 99, 'Silverado 3500', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 86, 'Borrego', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (113, 93, 'GTI', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 89, 'XLR-V', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (101, 84, 'Suburban 2500', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (192, 64, 'Crown Victoria', 2);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 81, 'Pajero', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 77, 'F250', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 65, 'Navigator', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 60, 'Galant', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (175, 83, 'Armada', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (251, 76, 'Suburban 2500', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (125, 68, 'Miata MX-5', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (169, 94, 'Expedition', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 83, 'Truck', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (275, 100, 'Safari', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (198, 65, 'Tundra', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (180, 70, 'LeMans', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (204, 85, 'XJ', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (132, 77, 'Savana 3500', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (271, 92, 'Matrix', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (259, 75, 'Golf', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (173, 77, 'Cougar', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (209, 85, 'Wrangler', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (225, 100, 'Grand Am', 45);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (209, 64, 'Pathfinder', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (174, 93, 'Explorer Sport Trac', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 66, 'Liberty', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 64, 'Tundra', 80);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (195, 75, 'Tracer', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (269, 60, 'CTS', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 79, 'Ram Wagon B150', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (128, 67, '626', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (107, 70, 'G-Series G10', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (257, 77, '1 Series', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (211, 95, 'Edge', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (272, 90, 'Ascender', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 83, 'Dakota', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 69, 'Fusion', 3);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (205, 79, 'Seville', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 78, 'Firebird', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (241, 68, 'F350', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (251, 100, 'Ram 3500', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (221, 64, 'Safari', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (218, 100, 'Camry Solara', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (120, 75, 'TT', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (264, 92, 'Express 1500', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (152, 75, 'S-Class', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (197, 62, 'F-Series', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (161, 88, 'E150', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (208, 97, 'Spectra', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (268, 61, '599 GTB Fiorano', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 78, '9000', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (185, 76, '740', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (174, 66, 'T100', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 68, 'Accent', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 100, 'Golf', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (216, 95, 'Leganza', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (124, 80, 'Range Rover', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (285, 87, 'Cavalier', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (164, 61, 'Patriot', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (291, 77, 'RSX', 75);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (190, 86, 'Endeavor', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (206, 78, 'Sidekick', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (230, 87, 'Rodeo', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (230, 67, '62', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 100, '190E', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 74, 'Vandura G3500', 93);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 92, 'Esprit', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (114, 99, 'Ghost', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (224, 80, 'LeSabre', 81);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (212, 92, 'Cougar', 70);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (232, 87, '5 Series', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (142, 93, 'Skyhawk', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (294, 100, 'Alcyone SVX', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (143, 74, 'Touareg', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 68, 'Spirit', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (211, 69, 'Grand Vitara', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (235, 80, 'Sierra 1500', 15);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (220, 73, 'Edge', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 87, 'Venture', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 64, 'S90', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 72, 'Q', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 97, 'Firebird', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (224, 88, 'Savana 2500', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (251, 71, 'Seville', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (137, 89, '2500 Club Coupe', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 60, 'W201', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (129, 61, 'Frontier', 82);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 99, 'Altima', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 62, 'IS-F', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (232, 84, 'SLK-Class', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 81, 'Tempest', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (139, 63, 'Type 2', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (263, 83, 'A4', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (284, 84, 'Envoy', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 89, 'G-Class', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (204, 82, 'QX', 91);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (250, 66, 'Ram 2500', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (282, 84, 'LS', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (130, 97, 'Insight', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (253, 87, 'Prius', 61);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 67, 'Panamera', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (125, 97, 'Outback Sport', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (274, 69, 'Dakota', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 88, '940', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (258, 69, 'F-Series', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 80, 'D350 Club', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (211, 100, 'Metro', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 75, 'Mighty Max Macro', 91);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (284, 68, 'Accent', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (267, 60, 'Suburban 2500', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 91, 'E-Series', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (295, 80, 'MR2', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (256, 97, 'Mustang', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (172, 61, 'Stealth', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (283, 82, 'M3', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (293, 91, 'Spectra', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 62, 'Biturbo', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 95, 'Vigor', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (114, 74, 'Ram 3500', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (161, 74, 'Caravan', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (210, 95, 'Bonneville', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 63, 'G-Series G20', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (279, 83, 'Expedition', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (277, 94, 'Continental', 53);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (209, 61, 'Mustang', 14);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (217, 75, 'Vantage', 77);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 100, '5000S', 26);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 93, 'Diamante', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 78, 'Sportage', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (147, 74, 'Swift', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (260, 91, 'Malibu', 28);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (289, 80, 'Sierra 3500', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (119, 98, '650', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (275, 70, 'Envoy', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (246, 69, 'Taurus', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (112, 78, 'DTS', 43);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (193, 77, 'F250', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 82, 'Century', 44);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (141, 62, 'Continental', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (226, 74, 'riolet', 33);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (157, 71, 'CX-5', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (264, 95, '4Runner', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (148, 100, '6 Series', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (238, 71, 'Crown Victoria', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 63, 'Canyon', 58);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (159, 70, 'XK Series', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (101, 77, 'Sportage', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (199, 85, 'Jetta', 19);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (129, 99, 'Brat', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (299, 90, 'G8', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (220, 95, 'Escape', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 92, 'Jetta', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (164, 72, 'Topaz', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (276, 71, 'M', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (112, 65, 'Aerio', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (277, 95, 'Jetta', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 86, 'MX-5', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (247, 82, 'Aveo', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (272, 90, 'Escape', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (268, 62, 'V8', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (222, 85, 'Grand Caravan', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (201, 69, 'B-Series Plus', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (288, 100, 'RSX', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (262, 60, 'Type 2', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 94, 'GTI', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (231, 91, 'Escort', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (142, 76, 'X5', 79);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (286, 60, 'XC90', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 98, 'Jetta III', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (286, 82, 'Escalade', 90);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (214, 78, 'F-Series', 40);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (264, 98, '911', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (279, 60, 'Express 3500', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (114, 83, 'QX', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (247, 67, 'Silverado 3500', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (245, 90, 'Grand Cherokee', 39);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (284, 80, 'V70', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (276, 75, 'E-Series', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (144, 94, 'Bonneville', 91);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (162, 72, 'IS', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (265, 61, 'PT Cruiser', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (266, 92, 'Pajero', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (230, 97, '200SX', 23);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (280, 60, 'M-Class', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 93, 'LeSabre', 10);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (219, 88, 'GTO', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 63, 'Range Rover', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (283, 84, 'Escort', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (267, 64, 'Ram 1500', 69);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (191, 89, 'Probe', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (296, 86, 'B-Series', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 93, 'Escalade ESV', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (213, 97, 'Bronco II', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (155, 76, 'E-Class', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (172, 73, 'Econoline E350', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (155, 70, 'Continental GTC', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 77, 'CX-9', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 67, 'X5', 8);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (206, 64, 'Accord', 74);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (152, 73, 'Sentra', 86);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (246, 75, 'XK', 4);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (186, 77, 'Esprit', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (112, 72, 'Avalon', 12);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (119, 87, 'Q7', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (275, 70, 'Explorer', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (133, 94, 'RL', 18);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (153, 96, 'Previa', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (136, 74, 'Bravada', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (151, 73, 'LeMans', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (273, 86, 'Impala SS', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (145, 96, 'Galant', 30);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (167, 69, 'Prelude', 41);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (248, 84, 'Skylark', 78);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (223, 64, 'Mazda5', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (284, 98, 'S-Class', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (255, 79, 'X6', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (131, 96, '760', 59);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (144, 72, 'Villager', 7);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (150, 100, 'SC', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (103, 67, 'Marquis', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (177, 62, 'Mazda6', 78);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (133, 85, 'TL', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (251, 70, '300ZX', 25);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (285, 61, 'Achieva', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (261, 78, 'Kizashi', 29);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (221, 97, 'GT', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (115, 60, 'Rendezvous', 78);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (260, 62, 'IS F', 49);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 67, 'F430', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 84, 'riolet', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (241, 65, 'Caravan', 92);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (295, 65, 'Corvette', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (169, 80, '911', 88);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (107, 74, 'GS', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (257, 70, 'Countach', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (208, 70, 'MPV', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (117, 68, 'Ram', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (163, 98, 'X-90', 46);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (160, 71, 'GranTurismo', 89);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 88, 'MKX', 5);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (195, 86, 'Galant', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (261, 64, 'Durango', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (130, 94, 'Tercel', 98);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (273, 63, 'Prius', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (111, 94, 'Corrado', 54);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (268, 81, 'G', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 76, 'Odyssey', 81);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (221, 97, 'FJ Cruiser', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (138, 84, 'Caravan', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (168, 77, 'Breeze', 72);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (166, 91, 'Chariot', 83);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (128, 70, 'New Yorker', 48);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (184, 68, 'F250', 76);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (192, 91, '350Z', 51);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (131, 86, 'Tracer', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (136, 77, 'F150', 17);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (198, 75, 'Vandura 3500', 67);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (107, 85, 'Express 1500', 85);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 79, 'Legend', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (281, 63, 'Aztek', 6);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (123, 84, 'i-290', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (280, 99, 'New Beetle', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (132, 79, 'Frontier', 57);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 64, 'Civic', 66);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (201, 100, 'Landaulet', 84);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (200, 61, 'Dakota', 13);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (102, 84, '2500 Club Coupe', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (127, 79, 'Vantage', 94);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (107, 92, 'Corvette', 56);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (178, 65, 'GranTurismo', 50);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (243, 92, 'Rondo', 55);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (288, 87, 'CR-V', 71);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 79, '960', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (295, 92, 'Camaro', 96);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (189, 77, 'LaCrosse', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (297, 76, 'Silhouette', 100);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (163, 64, 'Miata MX-5', 97);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (290, 83, 'CR-V', 34);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (216, 81, 'Rally Wagon G3500', 65);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (149, 68, 'Solara', 81);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 71, 'Flex', 87);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (118, 97, 'Boxster', 14);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 91, 'H1', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (160, 60, 'Rodeo', 22);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (292, 74, 'G', 81);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (290, 63, 'E-Class', 73);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (163, 69, 'G', 16);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (130, 97, 'Aztek', 95);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (210, 88, 'Rodeo', 1);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (116, 84, 'MKZ', 36);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (189, 74, 'F150', 52);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (230, 61, 'Starion', 24);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (101, 97, 'Altima', 68);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (239, 95, 'Civic', 47);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (254, 87, 'DeVille', 20);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (205, 61, 'Exige', 70);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (188, 74, 'Accent', 78);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (237, 99, 'H1', 32);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (273, 94, 'Reno', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (158, 60, '6 Series', 11);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (110, 92, 'XL-7', 35);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (205, 71, 'Mazda5', 60);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (113, 62, 'Bonneville', 62);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (134, 67, 'Silverado 2500', 31);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (170, 76, 'S-Type', 37);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (269, 64, 'Rio', 21);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (176, 76, 'Corvette', 63);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (182, 84, 'Grand Am', 38);
insert into aviones (capacidad, peso, modelo, id_aerolinea_fk) values (203, 68, '7 Series', 34);
