insert into aerolineas (nombre, estado) values ('Reichert-Koelpin', true);
insert into aerolineas (nombre, estado) values ('Hilll-Ryan', false);
insert into aerolineas (nombre, estado) values ('Rohan Group', true);
insert into aerolineas (nombre, estado) values ('Carter-Reynolds', true);
insert into aerolineas (nombre, estado) values ('Reynolds-Kunde', false);
insert into aerolineas (nombre, estado) values ('White Group', true);
insert into aerolineas (nombre, estado) values ('Auer, Lakin and Jacobi', false);
insert into aerolineas (nombre, estado) values ('Waelchi, Trantow and Rath', true);
insert into aerolineas (nombre, estado) values ('Ledner, Mayert and Kutch', false);
insert into aerolineas (nombre, estado) values ('Will LLC', true);
insert into aerolineas (nombre, estado) values ('Toy LLC', true);
insert into aerolineas (nombre, estado) values ('Pacocha and Sons', false);
insert into aerolineas (nombre, estado) values ('Sauer-Hills', true);
insert into aerolineas (nombre, estado) values ('Hoppe, Gleichner and Beahan', true);
insert into aerolineas (nombre, estado) values ('Berge, Rohan and Lakin', true);
insert into aerolineas (nombre, estado) values ('Bruen, Harvey and Bradtke', true);
insert into aerolineas (nombre, estado) values ('Mosciski-Barton', true);
insert into aerolineas (nombre, estado) values ('Hintz, Howell and Halvorson', true);
insert into aerolineas (nombre, estado) values ('Ritchie, Hettinger and Russel', false);
insert into aerolineas (nombre, estado) values ('Labadie, Schulist and Kassulke', false);
insert into aerolineas (nombre, estado) values ('VonRueden Inc', false);
insert into aerolineas (nombre, estado) values ('Hettinger and Sons', true);
insert into aerolineas (nombre, estado) values ('Hessel LLC', true);
insert into aerolineas (nombre, estado) values ('Paucek-Morar', false);
insert into aerolineas (nombre, estado) values ('Pouros LLC', true);
insert into aerolineas (nombre, estado) values ('Nikolaus and Sons', true);
insert into aerolineas (nombre, estado) values ('Bayer-Homenick', true);
insert into aerolineas (nombre, estado) values ('Fahey Inc', false);
insert into aerolineas (nombre, estado) values ('Halvorson and Sons', true);
insert into aerolineas (nombre, estado) values ('Kuphal-Waelchi', true);
insert into aerolineas (nombre, estado) values ('Quitzon-Ortiz', true);
insert into aerolineas (nombre, estado) values ('Tillman LLC', false);
insert into aerolineas (nombre, estado) values ('Harvey, Tromp and Collier', true);
insert into aerolineas (nombre, estado) values ('Jaskolski, Lind and Johnston', true);
insert into aerolineas (nombre, estado) values ('Koelpin, Purdy and Jones', true);
insert into aerolineas (nombre, estado) values ('Paucek-Dooley', false);
insert into aerolineas (nombre, estado) values ('Padberg, Brown and Hand', false);
insert into aerolineas (nombre, estado) values ('Bednar, Thiel and Barton', true);
insert into aerolineas (nombre, estado) values ('Purdy-Greenfelder', true);
insert into aerolineas (nombre, estado) values ('Graham Inc', true);


insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('LeBaron', 275, false, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('LHS', 144, true, 11);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Spectra', 178, false, 2);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Protege5', 229, true, 37);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Tracker', 125, true, 8);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Legacy', 260, true, 2);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Azure', 142, true, 24);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('A6', 210, true, 30);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Neon', 140, false, 26);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('X5', 252, false, 32);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Gallardo', 172, true, 21);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Esprit', 243, false, 19);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('G25', 135, true, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('MPV', 197, true, 17);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Cobalt SS', 263, false, 24);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Sonoma Club Coupe', 281, false, 11);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Ciera', 185, false, 27);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Impreza', 283, false, 13);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('4Runner', 175, false, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Spyder', 273, false, 6);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Volt', 232, false, 31);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Maxima', 102, true, 8);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Tracker', 124, false, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('CTS-V', 252, false, 24);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Transit Connect', 217, true, 11);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Scoupe', 136, true, 24);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Sebring', 183, false, 29);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Durango', 272, true, 15);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('S-Class', 237, false, 34);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('FX', 125, true, 4);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Rio', 118, true, 8);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Insight', 217, false, 26);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('SC', 286, true, 6);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Mazda3', 262, true, 27);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('9-3', 215, true, 2);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('LeSabre', 272, false, 1);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Taurus', 209, false, 10);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Taurus', 183, false, 43);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('JX', 127, false, 38);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Lancer Evolution', 153, false, 2);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Camry', 283, true, 42);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Boxster', 175, false, 7);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('A6', 180, false, 17);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('GLK-Class', 267, false, 23);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Camry Hybrid', 184, true, 7);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('A8', 230, true, 17);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Protege', 151, false, 19);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Elantra', 234, true, 10);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Tucson', 237, false, 24);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Eldorado', 231, true, 1);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Edge', 230, false, 5);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Spectra', 106, false, 31);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Z4', 190, false, 22);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('F-Series', 198, true, 19);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Ram 3500', 232, true, 32);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Civic', 101, true, 38);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Escape', 249, true, 25);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Fit', 252, true, 1);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Rio5', 290, false, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Highlander', 199, false, 43);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Voyager', 151, false, 34);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Insight', 186, false, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('C70', 255, false, 12);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('M', 143, false, 34);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('300', 166, true, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Mazda6', 296, true, 20);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('TT', 189, true, 11);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Wrangler', 109, true, 7);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Yukon', 288, false, 24);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('SC', 241, false, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('XK Series', 218, true, 10);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Firebird', 211, true, 27);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('525', 299, false, 15);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('3 Series', 298, true, 18);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Town Car', 147, true, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Silverado 1500', 170, false, 4);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('V8 Vantage', 175, false, 43);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('C70', 127, true, 18);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Freelander', 230, true, 19);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('S2000', 171, false, 42);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('5 Series', 107, false, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Imperial', 151, false, 30);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Precis', 175, false, 25);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('S60', 250, true, 7);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('DBS', 165, false, 26);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('9000', 109, false, 3);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Town Car', 138, false, 17);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Montero', 147, true, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Suburban 1500', 159, false, 21);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Club Wagon', 208, false, 30);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Ghost', 262, true, 20);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('IS', 258, false, 6);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Mustang', 237, false, 42);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Tacoma', 235, true, 15);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Gallardo', 104, false, 40);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Courier', 287, false, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('X3', 110, true, 14);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Rio5', 124, true, 16);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Lanos', 192, false, 28);
insert into aviones (modelo, capacidad, estado, id_aerolinea) values ('Regal', 222, false, 18);